Repository APPS-sookmyung/2024-OUTFOOT-Server, pull requests merged in 2024-08, with the labels that each got.

#33 [Feat] 컨트롤러 스웨거 애노테이션 추가
  src/main/java/outfoot/outfootserver/checkpage/controller/CheckPageController.java
  src/main/java/outfoot/outfootserver/emotion/controller/DislikeController.java
  src/main/java/outfoot/outfootserver/emotion/controller/LikeController.java
  src/main/java/outfoot/outfootserver/member/controller/MemberController.java
Labels: 🚨MVP, 🔆아정, ⚒️fix

#37 [Feat] Swagger 애노테이션 및 도커 파일 추가
  Dockerfile
  build.gradle
  src/main/java/outfoot/outfootserver/HealthCheck.java
  src/main/java/outfoot/outfootserver/checkpage/controller/CheckPageController.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageListResponse.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageRequest.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageResponse.java
  src/main/java/outfoot/outfootserver/config/SwaggerConfig.java
  src/main/java/outfoot/outfootserver/confirm/controller/ConfirmController.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmListResponse.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmRequest.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmResponse.java
  src/main/java/outfoot/outfootserver/confirm/dto/UpdateConfirmRequest.java
  src/main/java/outfoot/outfootserver/emotion/controller/DislikeController.java
  src/main/java/outfoot/outfootserver/emotion/controller/LikeController.java
  src/main/java/outfoot/outfootserver/friend/controller/FriendController.java
  src/main/java/outfoot/outfootserver/friend/dto/AddFriendRequest.java
  src/main/java/outfoot/outfootserver/friend/dto/FriendListResponse.java
  src/main/java/outfoot/outfootserver/member/controller/MemberController.java
  src/main/java/outfoot/outfootserver/member/dto/MemberResponse.java
  src/main/java/outfoot/outfootserver/member/dto/SignUpRequest.java
Labels: ✨feature, 🚨MVP, 🔆아정

#38 [Feat] 스웨거 애노테이션 추가
  Dockerfile
  build.gradle
  src/main/java/outfoot/outfootserver/HealthCheck.java
  src/main/java/outfoot/outfootserver/checkpage/controller/CheckPageController.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageListResponse.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageRequest.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageResponse.java
  src/main/java/outfoot/outfootserver/config/SwaggerConfig.java
  src/main/java/outfoot/outfootserver/confirm/controller/ConfirmController.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmListResponse.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmRequest.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmResponse.java
  src/main/java/outfoot/outfootserver/confirm/dto/UpdateConfirmRequest.java
  src/main/java/outfoot/outfootserver/emotion/controller/DislikeController.java
  src/main/java/outfoot/outfootserver/emotion/controller/LikeController.java
  src/main/java/outfoot/outfootserver/friend/controller/FriendController.java
  src/main/java/outfoot/outfootserver/friend/dto/AddFriendRequest.java
  src/main/java/outfoot/outfootserver/friend/dto/FriendListResponse.java
  src/main/java/outfoot/outfootserver/member/controller/MemberController.java
  src/main/java/outfoot/outfootserver/member/dto/MemberResponse.java
  src/main/java/outfoot/outfootserver/member/dto/SignUpRequest.java
Labels: ✨feature, 🚨MVP, 🔆아정

#40 [Feat] S3 연동
  Dockerfile
  build.gradle
  gradlew
  src/main/java/outfoot/outfootserver/HealthCheck.java
  src/main/java/outfoot/outfootserver/files/FileUploader.java
  src/main/java/outfoot/outfootserver/files/S3Config.java
  src/main/java/outfoot/outfootserver/files/S3FileUploader.java
  src/main/java/outfoot/outfootserver/files/S3IOException.java
  src/main/java/outfoot/outfootserver/files/TestFileUploader.java
Labels: ✨feature, 🚨MVP, 🔆아정

#45 [Feat] workflows 생성
  .github/workflows/github-actions.yml
Labels: ✨feature, 🚨MVP, 🔆아정

#46 [Feat] CI/CD 추가
  .github/workflows/github-actions.yml
  Dockerfile
  build.gradle
  gradlew
  src/main/java/outfoot/outfootserver/HealthCheck.java
  src/main/java/outfoot/outfootserver/files/FileUploader.java
  src/main/java/outfoot/outfootserver/files/S3Config.java
  src/main/java/outfoot/outfootserver/files/S3FileUploader.java
  src/main/java/outfoot/outfootserver/files/S3IOException.java
  src/main/java/outfoot/outfootserver/files/TestFileUploader.java
Labels: ✨feature, 🚨MVP, 🔆아정

#47 [Fix] .env 파일 명령어 삭제
  .github/workflows/github-actions.yml
Labels: 🚨MVP, 🔆아정, ⚒️fix

#48 [Fix] .env 파일 명령어 삭제
  .github/workflows/github-actions.yml
Labels: 🚨MVP, 🔆아정, ⚒️fix

#49 [Fix] Java Version 수정
  .github/workflows/github-actions.yml
Labels: 🚨MVP, 🔆아정, ⚒️fix

#50 [Fix] Java Version 수정
  .github/workflows/github-actions.yml
Labels: 🚨MVP, 🔆아정, ⚒️fix

#51 [Fix] 포트번호 에러 수정
  .github/workflows/github-actions.yml
Labels: 🚨MVP, 🔆아정, ⚒️fix

#52 [Fix] 포트번호 에러 수정
  .github/workflows/github-actions.yml
Labels: 🚨MVP, 🔆아정, ⚒️fix

#53 [Fix] Dockerfile 수정
  Dockerfile
  resources/hello.txt
  resources/static/hello.html
Labels: 🚨MVP, 🔆아정, ⚒️fix

#55 [Del] Duplicate Service Test 제거
  src/test/java/outfoot/outfootserver/checkpage/service/CheckPageServiceTest.java
Labels: 🚨MVP, 🔆아정, ⚒️fix

#56 [Del] Duplicate Service Test 제거
  src/test/java/outfoot/outfootserver/checkpage/service/CheckPageServiceTest.java
Labels: 🚨MVP, 🔆아정, ⚒️fix

#57 [Fix] add secret key
  .github/workflows/github-actions.yml
Labels: 🚨MVP, 🔆아정, ⚒️fix

#58 [Fix] add secret key
  .github/workflows/github-actions.yml
Labels: 🚨MVP, 🔆아정, ⚒️fix

#62 [Fix] CI/CD 구축 오류 해결
  .DS_Store
  .github/workflows/github-actions.yml
Labels: 🚨MVP, 🔆아정, ⚒️fix

#63 [Fix] CI/CD 구축 오류 해결
  .DS_Store
  .github/workflows/github-actions.yml
Labels: 🚨MVP, 🔆아정, ⚒️fix

#64 [Fix] github action secrets key 제거
  .github/workflows/github-actions.yml
Labels: 🚨MVP, 🔆아정, ⚒️fix

#65 [Fix] github action secrets key 제거
  .github/workflows/github-actions.yml
Labels: 🚨MVP, 🔆아정, ⚒️fix

#66 [Fix] 깃허브 액션 트리거 브랜치 변경
  .github/workflows/github-actions.yml
Labels: 🚨MVP, 🔆아정, ⚒️fix

#43 [Fix] 도장판 조회 로직 수정
  src/main/java/outfoot/outfootserver/checkpage/controller/CheckPageController.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageCountListDto.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageListResponse.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageResponse.java
  src/main/java/outfoot/outfootserver/checkpage/service/CheckPageService.java
Labels: 🚨MVP, 🔆아정, ⚒️fix

#67 [Feat] 회원 중복 저장 예외 처리
  src/main/java/outfoot/outfootserver/common/GlobalExceptionHandler.java
  src/main/java/outfoot/outfootserver/member/service/MemberService.java
Labels: 🧸현서, ⚒️fix

#59 [Feat] 인증판 및 마이페이지 이미지 업로드 로직 구현
  src/main/java/outfoot/outfootserver/TestRequest.java
  src/main/java/outfoot/outfootserver/confirm/controller/ConfirmController.java
  src/main/java/outfoot/outfootserver/confirm/domain/Confirm.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmListResponse.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmRequest.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmResponse.java
  src/main/java/outfoot/outfootserver/confirm/dto/UpdateConfirmRequest.java
  src/main/java/outfoot/outfootserver/confirm/service/ConfirmService.java
  src/main/java/outfoot/outfootserver/files/TestFileUploader.java
  src/main/java/outfoot/outfootserver/member/controller/MemberController.java
  src/main/java/outfoot/outfootserver/member/domain/Member.java
  src/main/java/outfoot/outfootserver/member/dto/MemberResponse.java
  src/main/java/outfoot/outfootserver/member/dto/MyPageRequest.java
  src/main/java/outfoot/outfootserver/member/dto/MyPageResponse.java
  src/main/java/outfoot/outfootserver/member/exception/AuthErrorCode.java
  src/main/java/outfoot/outfootserver/member/service/MemberService.java
Labels: ✨feature, 🚨MVP, 🧸현서

#70 [Feat] 요구사항 수정
  .github/workflows/github-actions.yml
  src/main/java/outfoot/outfootserver/checkpage/controller/CheckPageController.java
  src/main/java/outfoot/outfootserver/checkpage/domain/Animal.java
  src/main/java/outfoot/outfootserver/checkpage/domain/CheckPage.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageListResponse.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageRequest.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageResponse.java
  src/main/java/outfoot/outfootserver/checkpage/service/CheckPageService.java
  src/main/java/outfoot/outfootserver/common/GlobalExceptionHandler.java
  src/main/java/outfoot/outfootserver/confirm/controller/ConfirmController.java
  src/main/java/outfoot/outfootserver/confirm/domain/Confirm.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmRequest.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmResponse.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmUpdateResponse.java
  src/main/java/outfoot/outfootserver/confirm/dto/UpdateConfirmRequest.java
  src/main/java/outfoot/outfootserver/confirm/exception/ConfirmErrorCode.java
  src/main/java/outfoot/outfootserver/confirm/repository/ConfirmRepository.java
  src/main/java/outfoot/outfootserver/confirm/service/ConfirmService.java
  src/main/java/outfoot/outfootserver/friend/controller/FriendController.java
  src/main/java/outfoot/outfootserver/friend/domain/Friend.java
  src/main/java/outfoot/outfootserver/friend/dto/AddFriendRequest.java
  src/main/java/outfoot/outfootserver/friend/dto/FriendCountListResponse.java
  src/main/java/outfoot/outfootserver/friend/dto/FriendListResponse.java
  src/main/java/outfoot/outfootserver/friend/exception/AuthException.java
  src/main/java/outfoot/outfootserver/friend/exception/FriendErrorCode.java
  src/main/java/outfoot/outfootserver/friend/exception/FriendException.java
  src/main/java/outfoot/outfootserver/friend/service/FriendService.java
  src/main/java/outfoot/outfootserver/member/controller/MemberController.java
  src/main/java/outfoot/outfootserver/member/domain/Member.java
  src/main/java/outfoot/outfootserver/member/dto/MyProfileResponse.java
  src/main/java/outfoot/outfootserver/member/dto/SignUpRequest.java
  src/main/java/outfoot/outfootserver/member/exception/AuthErrorCode.java
  src/main/java/outfoot/outfootserver/member/repository/MemberRepository.java
  src/main/java/outfoot/outfootserver/member/service/MemberService.java
  src/test/java/outfoot/outfootserver/checkpage/controller/CheckPageControllerTest.java
  src/test/java/outfoot/outfootserver/checkpage/domain/AnimalTest.java
  src/test/java/outfoot/outfootserver/checkpage/service/CheckPageServiceTest.java
Labels: 🚨MVP, 🔆아정, ⚒️fix

#71 [Deploy] 3차 배포
  .github/workflows/github-actions.yml
  src/main/java/outfoot/outfootserver/TestRequest.java
  src/main/java/outfoot/outfootserver/checkpage/controller/CheckPageController.java
  src/main/java/outfoot/outfootserver/checkpage/domain/Animal.java
  src/main/java/outfoot/outfootserver/checkpage/domain/CheckPage.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageCountListDto.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageListResponse.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageRequest.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageResponse.java
  src/main/java/outfoot/outfootserver/checkpage/service/CheckPageService.java
  src/main/java/outfoot/outfootserver/common/GlobalExceptionHandler.java
  src/main/java/outfoot/outfootserver/confirm/controller/ConfirmController.java
  src/main/java/outfoot/outfootserver/confirm/domain/Confirm.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmListResponse.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmRequest.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmResponse.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmUpdateResponse.java
  src/main/java/outfoot/outfootserver/confirm/dto/UpdateConfirmRequest.java
  src/main/java/outfoot/outfootserver/confirm/exception/ConfirmErrorCode.java
  src/main/java/outfoot/outfootserver/confirm/repository/ConfirmRepository.java
  src/main/java/outfoot/outfootserver/confirm/service/ConfirmService.java
  src/main/java/outfoot/outfootserver/files/TestFileUploader.java
  src/main/java/outfoot/outfootserver/friend/controller/FriendController.java
  src/main/java/outfoot/outfootserver/friend/domain/Friend.java
  src/main/java/outfoot/outfootserver/friend/dto/AddFriendRequest.java
  src/main/java/outfoot/outfootserver/friend/dto/FriendCountListResponse.java
  src/main/java/outfoot/outfootserver/friend/dto/FriendListResponse.java
  src/main/java/outfoot/outfootserver/friend/exception/AuthException.java
  src/main/java/outfoot/outfootserver/friend/exception/FriendErrorCode.java
  src/main/java/outfoot/outfootserver/friend/exception/FriendException.java
  src/main/java/outfoot/outfootserver/friend/service/FriendService.java
  src/main/java/outfoot/outfootserver/member/controller/MemberController.java
  src/main/java/outfoot/outfootserver/member/domain/Member.java
  src/main/java/outfoot/outfootserver/member/dto/MemberResponse.java
  src/main/java/outfoot/outfootserver/member/dto/MyPageRequest.java
  src/main/java/outfoot/outfootserver/member/dto/MyPageResponse.java
  src/main/java/outfoot/outfootserver/member/dto/MyProfileResponse.java
  src/main/java/outfoot/outfootserver/member/dto/SignUpRequest.java
  src/main/java/outfoot/outfootserver/member/exception/AuthErrorCode.java
  src/main/java/outfoot/outfootserver/member/repository/MemberRepository.java
  src/main/java/outfoot/outfootserver/member/service/MemberService.java
  src/test/java/outfoot/outfootserver/checkpage/controller/CheckPageControllerTest.java
  src/test/java/outfoot/outfootserver/checkpage/domain/AnimalTest.java
  src/test/java/outfoot/outfootserver/checkpage/service/CheckPageServiceTest.java
Labels: 🚨MVP, 🔆아정, ⚒️fix
