Repository APPS-sookmyung/2024-OUTFOOT-Server, pull requests merged in 2024-07, with the labels that each got.

#12 [Feat] 칭찬판 관리 로직 구현
  src/main/java/outfoot/outfootserver/checkpage/controller/CheckPageController.java
  src/main/java/outfoot/outfootserver/checkpage/domain/Animal.java
  src/main/java/outfoot/outfootserver/checkpage/domain/CheckPage.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageListResponse.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageRequest.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageResponse.java
  src/main/java/outfoot/outfootserver/checkpage/exception/CheckPageErrorCode.java
  src/main/java/outfoot/outfootserver/checkpage/exception/CheckPageException.java
  src/main/java/outfoot/outfootserver/checkpage/repository/CheckPageRepository.java
  src/main/java/outfoot/outfootserver/checkpage/service/CheckPageService.java
  src/main/java/outfoot/outfootserver/common/GlobalExceptionHandler.java
Labels: ✨feature, 🚨MVP, 🔆아정

#19 [Feat] 도장판 Swagger 애노테이션 추가
  src/main/java/outfoot/outfootserver/checkpage/controller/CheckPageController.java
Labels: ✨feature, 🚨MVP, 🔆아정

#17 [Feat] 칭찬판 테스트 코드 작성
  src/main/java/outfoot/outfootserver/checkpage/controller/CheckPageController.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageRequest.java
  src/main/java/outfoot/outfootserver/checkpage/service/CheckPageService.java
  src/test/java/outfoot/outfootserver/ControllerTest.java
  src/test/java/outfoot/outfootserver/checkpage/controller/CheckPageControllerTest.java
  src/test/java/outfoot/outfootserver/checkpage/domain/AnimalTest.java
  src/test/java/outfoot/outfootserver/checkpage/service/CheckPageServiceTest.java
Labels: 🔆아정, ✏️test

#16 [FEAT] 친구 관리 로직 구현
  src/main/java/outfoot/outfootserver/friend/controller/FriendController.java
  src/main/java/outfoot/outfootserver/friend/domain/Friend.java
  src/main/java/outfoot/outfootserver/friend/dto/AddFriendRequest.java
  src/main/java/outfoot/outfootserver/friend/dto/FriendListResponse.java
  src/main/java/outfoot/outfootserver/friend/exception/AuthErrorCode.java
  src/main/java/outfoot/outfootserver/friend/exception/AuthException.java
  src/main/java/outfoot/outfootserver/friend/repository/FriendRepository.java
  src/main/java/outfoot/outfootserver/friend/service/FriendService.java
  src/main/java/outfoot/outfootserver/member/domain/Member.java
  src/main/java/outfoot/outfootserver/member/repository/MemberRepository.java
Labels: ✨feature, 🚨MVP, 🧸현서

#22 [Feat] 인정, 부정 로직 구현
  src/main/java/outfoot/outfootserver/checkpage/service/CheckPageService.java
  src/main/java/outfoot/outfootserver/common/GlobalExceptionHandler.java
  src/main/java/outfoot/outfootserver/confirm/ConfirmController.java
  src/main/java/outfoot/outfootserver/confirm/domain/Confirm.java
  src/main/java/outfoot/outfootserver/confirm/exception/ConfirmErrorCode.java
  src/main/java/outfoot/outfootserver/confirm/exception/ConfirmException.java
  src/main/java/outfoot/outfootserver/confirm/repository/ConfirmRepository.java
  src/main/java/outfoot/outfootserver/confirm/service/ConfirmService.java
  src/main/java/outfoot/outfootserver/emotion/controller/DislikeController.java
  src/main/java/outfoot/outfootserver/emotion/controller/LikeController.java
  src/main/java/outfoot/outfootserver/emotion/domain/Dislike.java
  src/main/java/outfoot/outfootserver/emotion/domain/Like.java
  src/main/java/outfoot/outfootserver/emotion/dto/EmotionRequest.java
  src/main/java/outfoot/outfootserver/emotion/exception/EmotionErrorCode.java
  src/main/java/outfoot/outfootserver/emotion/exception/EmotionException.java
  src/main/java/outfoot/outfootserver/emotion/repository/DislikeRepository.java
  src/main/java/outfoot/outfootserver/emotion/repository/LikeRepository.java
  src/main/java/outfoot/outfootserver/emotion/service/DislikeService.java
  src/main/java/outfoot/outfootserver/emotion/service/EmotionManageService.java
  src/main/java/outfoot/outfootserver/emotion/service/LikeService.java
  src/main/java/outfoot/outfootserver/member/exception/AuthErrorCode.java
  src/main/java/outfoot/outfootserver/member/service/MemberService.java
Labels: ✨feature, 🚨MVP, 🔆아정

#25 [Fix] EmotionManageService 로직 변경
  resources/hello.txt
  resources/static/hello.html
  src/main/java/outfoot/outfootserver/emotion/controller/DislikeController.java
  src/main/java/outfoot/outfootserver/emotion/controller/LikeController.java
  src/main/java/outfoot/outfootserver/emotion/dto/EmotionRequest.java
  src/main/java/outfoot/outfootserver/emotion/service/DislikeService.java
  src/main/java/outfoot/outfootserver/emotion/service/EmotionManageService.java
  src/main/java/outfoot/outfootserver/emotion/service/LikeService.java
Labels: 🚨MVP, 🔆아정, ⚒️fix

#28 [Fix] CheckPage 및 인정, 부정 로직 수정
  .gitignore
  src/main/java/outfoot/outfootserver/checkpage/domain/CheckPage.java
  src/main/java/outfoot/outfootserver/checkpage/service/CheckPageService.java
  src/main/java/outfoot/outfootserver/emotion/controller/DislikeController.java
  src/main/java/outfoot/outfootserver/emotion/controller/LikeController.java
  src/main/java/outfoot/outfootserver/emotion/domain/Dislike.java
  src/main/java/outfoot/outfootserver/emotion/domain/Like.java
  src/main/java/outfoot/outfootserver/emotion/dto/EmotionRequest.java
  src/main/java/outfoot/outfootserver/emotion/repository/DislikeRepository.java
  src/main/java/outfoot/outfootserver/emotion/repository/LikeRepository.java
  src/main/java/outfoot/outfootserver/emotion/service/DislikeService.java
  src/main/java/outfoot/outfootserver/emotion/service/EmotionManageService.java
  src/main/java/outfoot/outfootserver/emotion/service/LikeService.java
  src/main/java/outfoot/outfootserver/member/controller/MemberController.java
  src/main/java/outfoot/outfootserver/member/domain/Member.java
Labels: 🚨MVP, 🔆아정, ⚒️fix

#29 [FEAT] 인증판 관리 로직 구현
  src/main/java/outfoot/outfootserver/confirm/ConfirmController.java
  src/main/java/outfoot/outfootserver/confirm/controller/ConfirmController.java
  src/main/java/outfoot/outfootserver/confirm/domain/Confirm.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmListResponse.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmRequest.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmResponse.java
  src/main/java/outfoot/outfootserver/confirm/exception/ConfirmErrorCode.java
  src/main/java/outfoot/outfootserver/confirm/repository/ConfirmRepository.java
  src/main/java/outfoot/outfootserver/confirm/service/ConfirmService.java
  src/main/java/outfoot/outfootserver/emotion/service/DislikeService.java
  src/main/java/outfoot/outfootserver/emotion/service/LikeService.java
  src/main/java/outfoot/outfootserver/member/controller/MemberController.java
  src/main/java/outfoot/outfootserver/member/dto/MemberResponse.java
  src/main/java/outfoot/outfootserver/member/service/MemberService.java
Labels: ✨feature, 🚨MVP, 🧸현서

#30 [ Fix] 메모 수정
  src/main/java/outfoot/outfootserver/confirm/controller/ConfirmController.java
  src/main/java/outfoot/outfootserver/confirm/dto/UpdateConfirmRequest.java
  src/main/java/outfoot/outfootserver/emotion/service/DislikeService.java
  src/main/java/outfoot/outfootserver/emotion/service/LikeService.java
Labels: 🚨MVP, 🔆아정, ⚒️fix
