Repository APPS-sookmyung/2024-OUTFOOT-Server, pull requests merged in 2024-09, with the labels that each got.

#85 [Fix] memberId 제거
  src/main/java/outfoot/outfootserver/checkpage/controller/CheckPageController.java
  src/main/java/outfoot/outfootserver/emotion/controller/DislikeController.java
  src/main/java/outfoot/outfootserver/emotion/controller/LikeController.java
  src/main/java/outfoot/outfootserver/exception/TokenErrorCode.java
  src/main/java/outfoot/outfootserver/member/controller/MemberController.java
  src/main/java/outfoot/outfootserver/member/service/MemberService.java
  src/main/java/outfoot/outfootserver/service/JwtService.java
Labels: 🚨MVP, 🔆아정, ⚒️fix

#87 [Feat] Confirm memberId 추출
  src/main/java/outfoot/outfootserver/confirm/controller/ConfirmController.java
  src/main/java/outfoot/outfootserver/friend/controller/FriendController.java
Labels: 🚨MVP, 🧸현서, ⚒️fix

#89 [Fix] 로그인 오류 수정
  src/main/java/outfoot/outfootserver/member/domain/Member.java
  src/main/java/outfoot/outfootserver/member/service/MemberService.java
  src/main/java/outfoot/outfootserver/service/JwtService.java
  src/main/java/outfoot/outfootserver/token/Controller/TokenController.java
  src/main/java/outfoot/outfootserver/token/Service/TokenService.java
  src/main/java/outfoot/outfootserver/token/dto/TokenResponse.java
Labels: 🚨MVP, 🐧지은, ⚒️fix

#90 [Feat] 예외 처리 코드 추가
  src/main/java/outfoot/outfootserver/checkpage/service/CheckPageService.java
  src/main/java/outfoot/outfootserver/member/exception/AuthErrorCode.java
Labels: ✨feature, 🚨MVP, 🔆아정

#92 [Feat] CheckPage 익셉션 처리
  src/main/java/outfoot/outfootserver/checkpage/controller/CheckPageController.java
  src/main/java/outfoot/outfootserver/checkpage/repository/CheckPageRepository.java
  src/main/java/outfoot/outfootserver/checkpage/service/CheckPageService.java
Labels: ✨feature, 🚨MVP, 🔆아정

#94 [Feat] 컨펌 로직 익셉션 처리
  src/main/java/outfoot/outfootserver/confirm/service/ConfirmService.java
Labels: ✨feature, 🚨MVP, 🔆아정

#93 [Fix] 친구 memberId, 응답 수정
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmUpdateResponse.java
  src/main/java/outfoot/outfootserver/friend/controller/FriendController.java
Labels: 🚨MVP, 🧸현서, ⚒️fix

#97 [Feat] 4차 배포
  .DS_Store
  src/main/java/outfoot/outfootserver/auth/application/OAuthLoginSuccessHandler.java
  src/main/java/outfoot/outfootserver/checkpage/controller/CheckPageController.java
  src/main/java/outfoot/outfootserver/checkpage/domain/CheckPage.java
  src/main/java/outfoot/outfootserver/checkpage/dto/CheckPageRequest.java
  src/main/java/outfoot/outfootserver/checkpage/repository/CheckPageRepository.java
  src/main/java/outfoot/outfootserver/checkpage/service/CheckPageService.java
  src/main/java/outfoot/outfootserver/common/GlobalExceptionHandler.java
  src/main/java/outfoot/outfootserver/config/SecurityConfig.java
  src/main/java/outfoot/outfootserver/confirm/controller/ConfirmController.java
  src/main/java/outfoot/outfootserver/confirm/domain/Confirm.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmRequest.java
  src/main/java/outfoot/outfootserver/confirm/dto/ConfirmUpdateResponse.java
  src/main/java/outfoot/outfootserver/confirm/repository/ConfirmRepository.java
  src/main/java/outfoot/outfootserver/confirm/service/ConfirmService.java
  src/main/java/outfoot/outfootserver/emotion/controller/DislikeController.java
  src/main/java/outfoot/outfootserver/emotion/controller/LikeController.java
  src/main/java/outfoot/outfootserver/exception/TokenErrorCode.java
  src/main/java/outfoot/outfootserver/exception/TokenErrorResult.java
  src/main/java/outfoot/outfootserver/exception/TokenException.java
  src/main/java/outfoot/outfootserver/friend/controller/FriendController.java
  src/main/java/outfoot/outfootserver/friend/domain/Friend.java
  src/main/java/outfoot/outfootserver/friend/repository/FriendRepository.java
  src/main/java/outfoot/outfootserver/friend/service/FriendService.java
  src/main/java/outfoot/outfootserver/member/controller/MemberController.java
  src/main/java/outfoot/outfootserver/member/domain/Member.java
  src/main/java/outfoot/outfootserver/member/dto/MemberResponse.java
  src/main/java/outfoot/outfootserver/member/dto/SignUpRequest.java
  src/main/java/outfoot/outfootserver/member/exception/AuthErrorCode.java
  src/main/java/outfoot/outfootserver/member/repository/MemberRepository.java
  src/main/java/outfoot/outfootserver/member/service/MemberService.java
  src/main/java/outfoot/outfootserver/service/JwtService.java
  src/main/java/outfoot/outfootserver/token/Controller/TokenController.java
  src/main/java/outfoot/outfootserver/token/Service/TokenService.java
  src/main/java/outfoot/outfootserver/token/domain/RefreshToken.java
  src/main/java/outfoot/outfootserver/token/dto/TokenResponse.java
  src/main/java/outfoot/outfootserver/token/repository/RefreshTokenRepository.java
Labels: ✨feature, 🚨MVP
